### ISSUE TITLE
Suggested modifications to summary description

### ISSUE THREAD

**Issue by allaway** [greenelab/nf1_inactivation#1]
I just have a few change suggestions for the Summary section - correcting a couple of typos and some conceptual stuff regarding NF1.

Original:

> The repository contains instructions to replicate and build upon a classifier trained to detect an NF1 inactivation signature in glioblastoma gene expression data. We leverage publicly available data from the Cancer Genome Atlas (TCGA) to tune a logistic classifier with an elastic net penalty using stochastic gradient descent. NF1 is a tumor supressor that regulates RAS (a well characterized oncogene). When NF1 is inactivated, RAS signalling continues unabated leading to uncontrolled cell growth. Patients with Neurofibromatosis type I (caused by germline NF1 mutations) have a predisposition for gliomas, and NF1 is one of the most commonly mutated gene in glioblastoma. However, NF1 can be inactivated either genetically or by proteosome (McGillicuddy et al. 2009) and thus, detecting when it is inactivated in patients is difficult. Because we have previously identified compounds that are synthetically lethal in NF1 inactivated cells (Wood et al. 2011) our ability to detect patients with NF1 inactivation signatures could inform treatment decisions.

With suggested changes: 

> The repository contains instructions to replicate and build upon a classifier trained to detect an NF1 inactivation signature in glioblastoma gene expression data. We leverage publicly available data from the Cancer Genome Atlas (TCGA) to tune a logistic classifier with an elastic net penalty using stochastic gradient descent. NF1 is a tumor suppressor that regulates RAS (a well characterized oncogene). When NF1 is inactivated, RAS signaling continues unabated leading to uncontrolled cell growth. Patients with neurofibromatosis type I (caused by heterozygous germline mutation of _NF1_) have a predisposition for multiple tumor types including optic gliomas, pheochromocytomas, and malignant peripheral nerve sheath tumors. Furthermore, NF1 is one of the most commonly mutated genes in glioblastoma. NF1 can be inactivated genetically or by other mechanisms including microRNAs or targeted degradation by the proteosome (McGillicuddy et al. 2009) . Therefore, detecting inactivation solely by sequencing the _NF1_ gene can result in false negatives. Because we have previously identified compounds that are synthetically lethal in NF1 inactivated cells (Wood et al. 2011), the ability to detect patients with NF1 inactivation signatures could inform treatment decisions.

**Comment by gwaybio** [comment]
Looks good to me @allaway!
